### ISSUE TITLE
"Deploy to Netlify" template

### ISSUE THREAD

**Issue by freetonik** [freetonik/underblog#20]

**Comment by lucas-deangelis** [comment]
Hi, thank you for creating and sharing Underblog. It's exactly what I was looking for so I'm trying to give back a bit.

I've made a template for Netlify (https://github.com/lucas-deangelis/underblog-template). To build it I added the binary in the repo, however I'm not sure if it's the best solution. I tried using the docker command but when trying to deploy it I realized that Netlify doesn't have docker on their build images.

I know Netlify uses Hugo, which like Underblog is built with Go, but after searching a bit Hugo is installed on their build image (https://github.com/netlify/build-image/blob/xenial/Dockerfile). I don't know if downloading Underblog and building it with each deploy would be a better solution, or even if it's possible since Netlify uses Go 1.12.

**Comment by freetonik** [comment]
Hi!

I think using the binary is good. I'd prefer this template simply because it is guaranteed to work (the Underblog part, at least). Maybe, it's a good idea to have a Makefile which fetches the latest binary release from https://github.com/freetonik/underblog/releases/latest

**Comment by lucas-deangelis** [comment]
I've added a Makefile with a command to get the latest binary, and another to build the website. Now there's no need to have the binary in the repository.

**Comment by freetonik** [comment]
Great! I've added the "deploy to netlify" button to the readme (https://github.com/freetonik/underblog/blob/master/README.md)

FYI, it links to your repo, so please, keep the master branch buildable. Let me know if you'd want me to maintain a fork instead.

**Comment by lucas-deangelis** [comment]
Nice work! I don't plan on changing anything on my repo so it should always work and I'll keep it up to date. Feel free to fork it anytime though!
